/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-03-29 18:11:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class assignments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/tags/header.tag", Long.valueOf(1427652028384L));
    _jspx_dependants.put("/WEB-INF/views/init.jsp", Long.valueOf(1427652028393L));
    _jspx_dependants.put("/WEB-INF/tags/pageTemplate.tag", Long.valueOf(1427652028386L));
    _jspx_dependants.put("/WEB-INF/tags/taskSection.tag", Long.valueOf(1427652028387L));
    _jspx_dependants.put("/WEB-INF/tags/menu.tag", Long.valueOf(1427652028385L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_nrtl_005fpageTemplate_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_nrtl_005fpageTemplate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:pageTemplate
    org.apache.jsp.tag.webpageTemplate_tag _jspx_th_nrtl_005fpageTemplate_005f0 = (new org.apache.jsp.tag.webpageTemplate_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005fpageTemplate_005f0);
    _jspx_th_nrtl_005fpageTemplate_005f0.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005fpageTemplate_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_nrtl_005fpageTemplate_005f0, null));
    _jspx_th_nrtl_005fpageTemplate_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005fpageTemplate_005f0);
    return false;
  }

  private boolean _jspx_meth_nrtl_005fheader_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:header
    org.apache.jsp.tag.webheader_tag _jspx_th_nrtl_005fheader_005f0 = (new org.apache.jsp.tag.webheader_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005fheader_005f0);
    _jspx_th_nrtl_005fheader_005f0.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005fheader_005f0.setParent(_jspx_parent);
    _jspx_th_nrtl_005fheader_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_nrtl_005fheader_005f0, null));
    _jspx_th_nrtl_005fheader_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005fheader_005f0);
    return false;
  }

  private boolean _jspx_meth_nrtl_005ftaskSection_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:taskSection
    org.apache.jsp.tag.webtaskSection_tag _jspx_th_nrtl_005ftaskSection_005f0 = (new org.apache.jsp.tag.webtaskSection_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005ftaskSection_005f0);
    _jspx_th_nrtl_005ftaskSection_005f0.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005ftaskSection_005f0.setParent(_jspx_parent);
    // /WEB-INF/views/assignments.jsp(34,6) name = sectionId type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f0.setSectionId("joinTheNames");
    // /WEB-INF/views/assignments.jsp(34,6) name = heading type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f0.setHeading("1. Joining names");
    _jspx_th_nrtl_005ftaskSection_005f0.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_nrtl_005ftaskSection_005f0, null));
    _jspx_th_nrtl_005ftaskSection_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005ftaskSection_005f0);
    return false;
  }

  private boolean _jspx_meth_nrtl_005ftaskSection_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:taskSection
    org.apache.jsp.tag.webtaskSection_tag _jspx_th_nrtl_005ftaskSection_005f1 = (new org.apache.jsp.tag.webtaskSection_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005ftaskSection_005f1);
    _jspx_th_nrtl_005ftaskSection_005f1.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005ftaskSection_005f1.setParent(_jspx_parent);
    // /WEB-INF/views/assignments.jsp(38,6) name = sectionId type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f1.setSectionId("fixBug");
    // /WEB-INF/views/assignments.jsp(38,6) name = heading type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f1.setHeading("2. Bug, what bug?");
    _jspx_th_nrtl_005ftaskSection_005f1.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_nrtl_005ftaskSection_005f1, null));
    _jspx_th_nrtl_005ftaskSection_005f1.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005ftaskSection_005f1);
    return false;
  }

  private boolean _jspx_meth_nrtl_005ftaskSection_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:taskSection
    org.apache.jsp.tag.webtaskSection_tag _jspx_th_nrtl_005ftaskSection_005f2 = (new org.apache.jsp.tag.webtaskSection_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005ftaskSection_005f2);
    _jspx_th_nrtl_005ftaskSection_005f2.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005ftaskSection_005f2.setParent(_jspx_parent);
    // /WEB-INF/views/assignments.jsp(42,6) name = sectionId type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f2.setSectionId("employeeStartDate");
    // /WEB-INF/views/assignments.jsp(42,6) name = heading type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f2.setHeading("3. Seniority");
    _jspx_th_nrtl_005ftaskSection_005f2.setJspBody(new Helper( 4, _jspx_page_context, _jspx_th_nrtl_005ftaskSection_005f2, null));
    _jspx_th_nrtl_005ftaskSection_005f2.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005ftaskSection_005f2);
    return false;
  }

  private boolean _jspx_meth_nrtl_005ftaskSection_005f3(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:taskSection
    org.apache.jsp.tag.webtaskSection_tag _jspx_th_nrtl_005ftaskSection_005f3 = (new org.apache.jsp.tag.webtaskSection_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005ftaskSection_005f3);
    _jspx_th_nrtl_005ftaskSection_005f3.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005ftaskSection_005f3.setParent(_jspx_parent);
    // /WEB-INF/views/assignments.jsp(46,6) name = sectionId type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f3.setSectionId("hardcoded");
    // /WEB-INF/views/assignments.jsp(46,6) name = heading type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f3.setHeading("4. Hard-coded and buggy");
    _jspx_th_nrtl_005ftaskSection_005f3.setJspBody(new Helper( 5, _jspx_page_context, _jspx_th_nrtl_005ftaskSection_005f3, null));
    _jspx_th_nrtl_005ftaskSection_005f3.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005ftaskSection_005f3);
    return false;
  }

  private boolean _jspx_meth_nrtl_005ftaskSection_005f4(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:taskSection
    org.apache.jsp.tag.webtaskSection_tag _jspx_th_nrtl_005ftaskSection_005f4 = (new org.apache.jsp.tag.webtaskSection_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005ftaskSection_005f4);
    _jspx_th_nrtl_005ftaskSection_005f4.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005ftaskSection_005f4.setParent(_jspx_parent);
    // /WEB-INF/views/assignments.jsp(67,6) name = sectionId type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f4.setSectionId("timetable");
    // /WEB-INF/views/assignments.jsp(67,6) name = heading type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f4.setHeading("5. Time reporting");
    _jspx_th_nrtl_005ftaskSection_005f4.setJspBody(new Helper( 6, _jspx_page_context, _jspx_th_nrtl_005ftaskSection_005f4, null));
    _jspx_th_nrtl_005ftaskSection_005f4.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005ftaskSection_005f4);
    return false;
  }

  private boolean _jspx_meth_nrtl_005ftaskSection_005f5(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:taskSection
    org.apache.jsp.tag.webtaskSection_tag _jspx_th_nrtl_005ftaskSection_005f5 = (new org.apache.jsp.tag.webtaskSection_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005ftaskSection_005f5);
    _jspx_th_nrtl_005ftaskSection_005f5.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005ftaskSection_005f5.setParent(_jspx_parent);
    // /WEB-INF/views/assignments.jsp(72,6) name = sectionId type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f5.setSectionId("backup");
    // /WEB-INF/views/assignments.jsp(72,6) name = heading type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f5.setHeading("6. Who wants backups?");
    _jspx_th_nrtl_005ftaskSection_005f5.setJspBody(new Helper( 7, _jspx_page_context, _jspx_th_nrtl_005ftaskSection_005f5, null));
    _jspx_th_nrtl_005ftaskSection_005f5.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005ftaskSection_005f5);
    return false;
  }

  private boolean _jspx_meth_nrtl_005ftaskSection_005f6(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:taskSection
    org.apache.jsp.tag.webtaskSection_tag _jspx_th_nrtl_005ftaskSection_005f6 = (new org.apache.jsp.tag.webtaskSection_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005ftaskSection_005f6);
    _jspx_th_nrtl_005ftaskSection_005f6.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005ftaskSection_005f6.setParent(_jspx_parent);
    // /WEB-INF/views/assignments.jsp(76,6) name = sectionId type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f6.setSectionId("tempCheck");
    // /WEB-INF/views/assignments.jsp(76,6) name = heading type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f6.setHeading("7. Temp Check");
    _jspx_th_nrtl_005ftaskSection_005f6.setJspBody(new Helper( 8, _jspx_page_context, _jspx_th_nrtl_005ftaskSection_005f6, null));
    _jspx_th_nrtl_005ftaskSection_005f6.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005ftaskSection_005f6);
    return false;
  }

  private boolean _jspx_meth_nrtl_005ftaskSection_005f7(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nrtl:taskSection
    org.apache.jsp.tag.webtaskSection_tag _jspx_th_nrtl_005ftaskSection_005f7 = (new org.apache.jsp.tag.webtaskSection_tag());
    _jsp_instancemanager.newInstance(_jspx_th_nrtl_005ftaskSection_005f7);
    _jspx_th_nrtl_005ftaskSection_005f7.setJspContext(_jspx_page_context);
    _jspx_th_nrtl_005ftaskSection_005f7.setParent(_jspx_parent);
    // /WEB-INF/views/assignments.jsp(85,6) name = sectionId type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f7.setSectionId("accessLog");
    // /WEB-INF/views/assignments.jsp(85,6) name = heading type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_nrtl_005ftaskSection_005f7.setHeading("8. Access logging");
    _jspx_th_nrtl_005ftaskSection_005f7.setJspBody(new Helper( 9, _jspx_page_context, _jspx_th_nrtl_005ftaskSection_005f7, null));
    _jspx_th_nrtl_005ftaskSection_005f7.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_nrtl_005ftaskSection_005f7);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_nrtl_005fheader_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-md-12\">\r\n");
      out.write("      <h3>Story</h3>\r\n");
      out.write("      <p>Our client, Benson ordered an application from Warden of the Internet & Co. to evaluate the work quality of his employees.</p>\r\n");
      out.write("      <p>Unfortunately Warden of the Internet was unable to complete this development due to the actions of Mordecai and Rigby. Finally Benson came to us\r\n");
      out.write("      because he knows that we always get the job done.</p>\r\n");
      out.write("      <h3>Assignment</h3>\r\n");
      out.write("      <p>Below you can find 8 tasks that you need to complete to help us deliver to Benson. Complete as much as you can and if you feel you are\r\n");
      out.write("        finished or just don't have knowledge to go any further then ship it to us. If you happen to go beyond these tasks, please document all other improvements so we wouldn't miss them when we grade your solution.</p>\r\n");
      out.write("      <h3>How to submit your result</h3>\r\n");
      out.write("      <ol>\r\n");
      out.write("        <li>Open <b>build.gradle</b> and set your name to variable <b>ext.candidateName</b></li>\r\n");
      out.write("        <li>Run: <b>gradle zip</b></li>\r\n");
      out.write("        <li>Visit <a href=\"http://bit.ly/challenge_completed\">http://bit.ly/challenge_completed</a> and submit your solution\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li>The zip file with name \"employee-evaluation-app-solution-Your Name.zip\" generated to the project directory root by \"gradle zip\".</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ol>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <div class=\"col-md-9\">\r\n");
      out.write("      <!-- ### Employee and Project names  ### -->\r\n");
      out.write("      ");
      if (_jspx_meth_nrtl_005ftaskSection_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("      <!-- ### Bug, what bug ### -->\r\n");
      out.write("      ");
      if (_jspx_meth_nrtl_005ftaskSection_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("      <!-- ### Employee start date ### -->\r\n");
      out.write("      ");
      if (_jspx_meth_nrtl_005ftaskSection_005f2(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("      <!-- ### Hard-coded and buggy ### -->\r\n");
      out.write("      ");
      if (_jspx_meth_nrtl_005ftaskSection_005f3(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("      <!-- ### Time reporting ### -->\r\n");
      out.write("      ");
      if (_jspx_meth_nrtl_005ftaskSection_005f4(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("      <!-- ### Who wants backups ### -->\r\n");
      out.write("      ");
      if (_jspx_meth_nrtl_005ftaskSection_005f5(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("      <!-- ### Temp Check ### -->\r\n");
      out.write("      ");
      if (_jspx_meth_nrtl_005ftaskSection_005f6(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\t    <!-- ### Access logging ### -->\r\n");
      out.write("      ");
      if (_jspx_meth_nrtl_005ftaskSection_005f7(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("      <ul class=\"well nav nav-pills nav-stacked\" id=\"submenu\" bs-affix>\r\n");
      out.write("        <li style=\"display: none;\" id=\"templateMenuItem\"><a href=\"\"><i class=\"icon-chevron-right\"></i></a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    <h1>Assignment</h1>\r\n");
      out.write("  ");
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <p>In Record.java there are two methdos that previous development team did not finish. Can you write them? The Employee names must be ordered by salary and Project names ordered alphabetically.</p>\r\n");
      out.write("      ");
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <p>Deleting employee and project records does not work sometimes. For example Rigby cannot be deleted. Can you find out why and fix that?</p>\r\n");
      out.write("      ");
      return false;
    }
    public boolean invoke4( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <p>Employees should also have date when they started working in park. Add this field to database, model and to all other relevant classes. The front-end should display date using format dd.mm.yyyy</p>\r\n");
      out.write("      ");
      return false;
    }
    public boolean invoke5( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <p>On statistics page there should be statistics about all the projects but values don't change and some charts are wrong. We believe that some slacker just hardcoded some values.</p>\r\n");
      out.write("        <p>There should be following statistics:</p>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>The project with most records - this is simple enough, this is project that is attached to the most records.</li>\r\n");
      out.write("          <li>The worst executed project - the project where (VERY_NEGATIVE record count + NEGATIVE record count) - (VERY_POSITIVE record count + POSITIVE\r\n");
      out.write("          record count) is greatest</li>\r\n");
      out.write("          <li>The best executed project - the project where (VERY_POSITIVE record count + POSITIVE record count) - (VERY_NEGATIVE record count + NEGATIVE\r\n");
      out.write("            record count) is greatest</li>\r\n");
      out.write("          <li>Employees involved statistics - a bar chart showing number of employees involved in projects</li>\r\n");
      out.write("          <li>\r\n");
      out.write("            For every project:\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li>Satisfaction Records - how many VERY_NEGATIVE, NEGATIVE, VERY_POSITIVE or POSITIVE records every project has.</li>\r\n");
      out.write("              <li>Employees Records - how many VERY_NEGATIVE, NEGATIVE, VERY_POSITIVE or POSITIVE records every employee involved in a project has.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>Developers mumbled something that Controller is completed and some small piece of code still needs to be written...</p>\r\n");
      out.write("      ");
      return false;
    }
    public boolean invoke6( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <p>A simple timetable has been requested to track time, some basic code has been written, your task is to finish it.</p>\r\n");
      out.write("        <p>The timetable must show start date, end date and how many hours every employee worked on a project.</p>\r\n");
      out.write("      ");
      return false;
    }
    public boolean invoke7( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <p>Benson wants backups. Since the last time Rigby and Mordecai stole the book of records and modified it he is really concerned about security. He wants to have CSV backups of his records. Again, something has been developed but it is very incomplete. The CSV should contain same data as records list.</p>\r\n");
      out.write("      ");
      return false;
    }
    public boolean invoke8( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <p>\r\n");
      out.write("        Web request is usually handled by single thread that processes it and at some point it also executes the controller method. Project based statistics\r\n");
      out.write("        can take long time to query so Rigby suggested Benson that he should demand for software execution temps to get the job done faster. Just like he\r\n");
      out.write("        successfully used temps in <a href=\"https://www.youtube.com/watch?v=0FIxNtv_rQQ\">Temp Check</a> episode.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p>Your task is to execute each statistics returning method call in a separate thread so that database could process them in parallel. These methods include every StatisticsService call from method StatisticsController.getView()</p>\r\n");
      out.write("      ");
      return false;
    }
    public boolean invoke9( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <p>Benson wants to monitor the access to the application and for that he has requested a log file that contains action request information. Please write that code. You can use any output format for log row, but the log must contain basic request data.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p>Log files should not be large in size since Benson would like to email these logs to his security expert Peeps. As additional feature configure log rotation in a way that new log file is created every hour and no more than 5 files are preserved.</p>\r\n");
      out.write("        <p>For bonus points configure or implement a solution for automatically zipping these logs as well.</p>\r\n");
      out.write("      ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
          case 4:
            invoke4( out );
            break;
          case 5:
            invoke5( out );
            break;
          case 6:
            invoke6( out );
            break;
          case 7:
            invoke7( out );
            break;
          case 8:
            invoke8( out );
            break;
          case 9:
            invoke9( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
