/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-04-04 15:50:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class landing_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>QuikMason</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- jQuery -->\r\n");
      out.write("  <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("  <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"page-login\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"col-md-12\">\r\n");
      out.write("        <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/y6120QOlsfU\" frameborder=\"0\" allowfullscreen></iframe>\r\n");
      out.write("    </div>\r\n");
      out.write("    <a href=\"login\">Login</a>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <H1>\r\n");
      out.write("        <spring:message code=\"label.form.title\"></spring:message>\r\n");
      out.write("    </H1>\r\n");
      out.write("    <form:form modelAttribute=\"user\" method=\"POST\" enctype=\"utf8\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <tr>\r\n");
      out.write("       <td><label><spring:message code=\"label.user.firstName\"></spring:message>\r\n");
      out.write("            </label>\r\n");
      out.write("        </td>\r\n");
      out.write("       <td><form:input path=\"firstName\" value=\"\" /></td>\r\n");
      out.write("       <form:errors path=\"firstName\" element=\"div\"/>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td><label><spring:message code=\"label.user.lastName\"></spring:message>\r\n");
      out.write("            </label>\r\n");
      out.write("        </td>\r\n");
      out.write("       <td><form:input path=\"lastName\" value=\"\" /></td>\r\n");
      out.write("       <form:errors path=\"lastName\" element=\"div\" />\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td><label><spring:message code=\"label.user.email\"></spring:message>\r\n");
      out.write("            </label>\r\n");
      out.write("        </td>\r\n");
      out.write("       <td><form:input path=\"email\" value=\"\" /></td>\r\n");
      out.write("       <form:errors path=\"email\" element=\"div\" />\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td><label><spring:message code=\"label.user.password\"></spring:message>\r\n");
      out.write("            </label>\r\n");
      out.write("        </td>\r\n");
      out.write("       <td><form:input path=\"password\" value=\"\" type=\"password\" /></td>\r\n");
      out.write("       <form:errors path=\"password\" element=\"div\" />\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("       <td><label><spring:message code=\"label.user.confirmPass\"></spring:message>\r\n");
      out.write("            </label>\r\n");
      out.write("        </td>\r\n");
      out.write("       <td><form:input path=\"matchingPassword\" value=\"\" type=\"password\" /></td>\r\n");
      out.write("       <form:errors element=\"div\" />\r\n");
      out.write("   </tr>\r\n");
      out.write("        <button type=\"submit\"><spring:message code=\"label.form.submit\"></spring:message>\r\n");
      out.write("        </button>\r\n");
      out.write("    </form:form>\r\n");
      out.write("    <br>\r\n");
      out.write("    <a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("        <spring:message code=\"label.form.loginLink\"></spring:message>\r\n");
      out.write("    </a>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/landing.jsp(72,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("login.html");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
