/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-04-05 10:54:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class webmenu_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent {


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005feval_0026_005fvar_005fexpression_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _005fjspx_005ftagPool_005fs_005feval_0026_005fvar_005fexpression_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005feval_0026_005fvar_005fexpression_005fnobody.release();
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("<div class=\"navbar navbar-inverse navbar-static-top\">");
      out.write("<div class=\"container\">");
      out.write("<div class=\"navbar-header\">");
      out.write("<button data-target=\"#main-menu\" data-toggle=\"collapse\" type=\"button\" class=\"navbar-toggle collapsed\">");
      out.write("<span class=\"sr-only\">");
      out.write("Toggle navigation");
      out.write("</span>");
      out.write("<span class=\"icon-bar\">");
      out.write("</span>");
      out.write("<span class=\"icon-bar\">");
      out.write("</span>");
      out.write("<span class=\"icon-bar\">");
      out.write("</span>");
      out.write("</button>");
      out.write("<a class=\"navbar-brand\" href=\"/main\">");
      out.write("QuikMason");
      out.write("</a>");
      out.write("</div>");
      out.write("<div id=\"main-menu\" class=\"collapse navbar-collapse\">");
      out.write("<ul id=\"main-menu-left\" class=\"nav navbar-nav\">");
      out.write("<li>");
      out.write("<a href=\"/main\">");
      out.write("Main");
      out.write("</a>");
      out.write("</li>");
      out.write("<li>");
      out.write("<a href=\"/user\">");
      out.write("My page");
      out.write("</a>");
      out.write("</li>");
      out.write("</ul>");
      out.write("<ul id=\"user-actions\" class=\"nav navbar-nav navbar-right\">");
      if (_jspx_meth_s_005feval_005f0(_jspx_page_context))
        return;
      out.write("<li>");
      out.write("<a style=\"text-transform: none; font-size: 12px;\" href=\"#\">");
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null, false));
      out.write(')');
      out.write("</a>");
      out.write("</li>");
      out.write("<li>");
      out.write("<a style=\"text-transform: none;\" href=\"/logout\">");
      out.write("Log out ");
      out.write("</a>");
      out.write("</li>");
      out.write("</ul>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
      _jspDestroy();
    }
  }

  private boolean _jspx_meth_s_005feval_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_s_005feval_005f0 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fs_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_s_005feval_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005feval_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/menu.tag(26,107) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005feval_005f0.setVar("fullName");
    // /WEB-INF/tags/menu.tag(26,107) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005feval_005f0.setExpression("T(com.quikmason.user.UserUtil).getCurrentUser().getName()");
    int[] _jspx_push_body_count_s_005feval_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_s_005feval_005f0 = _jspx_th_s_005feval_005f0.doStartTag();
      if (_jspx_th_s_005feval_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_s_005feval_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_s_005feval_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_s_005feval_005f0.doFinally();
      _005fjspx_005ftagPool_005fs_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_s_005feval_005f0);
    }
    return false;
  }
}
