CREATE TABLE
    USER
    (
    	ID IDENTITY NOT NULL PRIMARY KEY,
        USERNAME VARCHAR(25) NOT NULL,
        PASSWORD VARCHAR(25) NOT NULL,
        FIRST_NAME VARCHAR(25) NOT NULL,
        LAST_NAME VARCHAR(25) NOT NULL,
        EMAIL VARCHAR(25)
    );