CREATE TABLE
    USER
    (
    	ID IDENTITY NOT NULL PRIMARY KEY,
        USERNAME VARCHAR(25) NOT NULL,
        PASSWORD VARCHAR(25) NOT NULL,
        FIRST_NAME VARCHAR(25) NOT NULL,
        LAST_NAME VARCHAR(25) NOT NULL,
        EMAIL VARCHAR(25)
    );
CREATE TABLE
    OFFER
    (
        ID IDENTITY NOT NULL PRIMARY KEY,
        COMPANY_NAME VARCHAR(255) NOT NULL,
        PHONE_NR VARCHAR(40) NOT NULL,
        MAIL VARCHAR(50) NOT NULL,
        START_DATE TIMESTAMP(2) DEFAULT CURRENT_TIMESTAMP NOT NULL,
        END_DATE TIMESTAMP(2) DEFAULT CURRENT_TIMESTAMP NOT NULL,
        ADDRESS VARCHAR(60) NOT NULL,
        OFFER_NAME VARCHAR(60) NOT NULL,
        WAGE REAL NOT NULL,
        CONTENT CLOB NOT NULL
    );